//FETCH DATA
export const VAV_COMPONENT_FETCH_PENDING = "VAV_COMPONENT_FETCH_PENDING";
export const VAV_COMPONENT_FETCH_FULFILLED = "VAV_COMPONENT_FETCH_FULFILLED";
export const VAV_COMPONENT_FETCH_REJECTED = "VAV_COMPONENT_FETCH_REJECTED";

//ACTIVATE COMPONENT ON CLICK
export const TOGGLE_VAV_COMPONENT_PENDING = "TOGGLE_VAV_COMPONENT_PENDING";
export const TOGGLE_VAV_COMPONENT_FULFILLED = "TOGGLE_VAV_COMPONENT_FULFILLED";
export const TOGGLE_VAV_COMPONENT_REJECTED = "TOGGLE_VAV_COMPONENT_REJECTED";

//ACTIVATE TAB ON CLICK
export const ACTIVATE_TAB_PENDING = "ACTIVATE_TAB_PENDING";
export const ACTIVATE_TAB_FULFILLED = "ACTIVATE_TAB_FULFILLED";
